name: attendence
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

#-----------------------PACKAGES-------------------------#

dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES
  http:
  intl:
  url_launcher:
  logger:

  #ICONS
  cupertino_icons: ^1.0.8
  flutter_svg:
  persistent_bottom_nav_bar: ^5.0.2
  snippet_coder_utils: ^1.0.15
  device_preview: ^1.1.0
  flutter_native_splash:
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  fluttertoast: ^8.2.5
  connectivity_plus: ^6.0.3
  #STATE MANAGEMENT


  get: ^4.6.6
  get_storage: ^2.1.1
  get_it: ^7.7.0
#PROJECT SPECIFIC

#-----------------------./PACKAGES END-------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #-----------------------LOCAL ASSETS-------------------------#
  assets:
    - assets/images/onbordingimages/
    - assets/icons/LoginIcons/
    - assets/LOGOS/
    - assets/icons/dark/
    - assets/icons/light/
    - assets/images/defaultimage/
    - assets/images/developerImage/


  #-----------------------LOCAL FONTS-------------------------#
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
